name: testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: run pyright
      run: pyright

  lint_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.12", "3.13"]  # include Archipelago min and max

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: lint with ruff
      run: ruff check .

    - name: unit tests with pytest
      run: pytest
